### ISSUE TITLE
[1.16.3] Client crash on clicking create world.

### ISSUE THREAD

**Issue by ProsperCraft** [TelepathicGrunt/Blame#2]
https://gist.github.com/ProsperCraft/7695ad362625b52ae084de9b890c6653
https://gist.github.com/ProsperCraft/caca7c3408e986c88dcccc7a3b9c1051

Removed blame and it quit crashing.

blame-1.16.3-1.4.0.jar
forge-1.16.3-34.1.12

**Comment by TelepathicGrunt** [comment]
Can you get me the full log instead of the crashlog?
You can find the full log in the logs folder above the mods folder and in there, I would like the latest.log file afte ryou reproduce the crash one more time. It'll help me know exactly when the crash occurs as this seems very odd. ~~Also, what other mods did you have on?~~

nvm on the modlist. I see it in the log lol. That's a lot of mods holy. Is it a modpack that I can download and test quickly? or can you export your mods so I can test with them?

**Comment by TelepathicGrunt** [comment]
Hey can you try this version of Blame? I think this should fix the issue. If so, I'll release this version. :)


[blame-1.16.3-1.4.2b.zip](https://github.com/TelepathicGrunt/Blame/files/5345226/blame-1.16.3-1.4.2b.zip)

**Comment by TelepathicGrunt** [comment]
Ok sorry about the message spam but 1.4.2 should fix this issue perfectly! I redid the code that caused the crash completely and it's now much, much better! :)

https://www.curseforge.com/minecraft/mc-mods/blame/files/3074617
