### ISSUE TITLE
[Suggestion] Diagnose Illegal Packet disconnects

### ISSUE THREAD

**Issue by LeakingAmps** [TelepathicGrunt/Blame#25]
I've been playing All The Mods recently and I'm having issues with random illegal packets disconnecting me once every few minutes. (5-10 minutes between disconnects in best circumstances). My sister and I can not figure out the issue. Blame doesn't seem to address this (and maybe it's out of your scope), but it would be very handy to know which of 200+ mods is randomly disconnecting me on that specific world.

**Comment by TelepathicGrunt** [comment]
While this is kinda within the scope of Blame, I have zero packet/networking knowledge and no idea how to even begin. I can ask if another modder would be willing to PR in a check but no promises. I wish I had better news sorry.

**Comment by noobanidus** [comment]
So, a mod-list would be required initially. Screenshots of the packet crashes as well as full debug logs from the server ***and*** the client (which will require you to launch it via the Minecraft launcher as all iterations of CurseForge launchers seem to suppress the debug log; I'm not sure about GDLauncher). In a lot of instances there's information on both sides that can help. 

That would a) provide a starting point for you finding out what your problem is, and b) provide a starting point in the packet crashing that could be used to inject code to that gives better information.

**Comment by TelepathicGrunt** [comment]
In addition to getting and sharing the debug log file as said by nooby, which is the only place with packet info, you should try xlpackets as well in case it is the packets being too large as well.
https://www.curseforge.com/minecraft/mc-mods/xl-packets

**Comment by TelepathicGrunt** [comment]
@fwyrl any new info? Did our debugging suggestions help?

**Comment by LeakingAmps** [comment]
I tried using XL packets, but that did not seem to help. Unfortunately, my sister has not been online in almost 2 weeks (we've only played once since I posted this), and I've not managed to get a debug log from her.

I'll update once I've got more info, sorry about that ^_^;

**Comment by TelepathicGrunt** [comment]
I'll be closing this as I cant seem to find where to get info on illegal packets and I wasnt able to get a debug log file of the issue. Rip
