### ISSUE TITLE
Change type of message from error to info.

### ISSUE THREAD

**Issue by K0-RR** [TelepathicGrunt/Blame#26]
`[main/ERROR]: Blame 1.16.4-2.4.1 initialized`
I think it would be better to use info because that's what other mods use to inform about launch. Btw why is this even printed? Can"t I just see the mod in the ModMenu?

**Comment by TelepathicGrunt** [comment]
This mod is for debugging issues and logging as error isn’t really going to cause any issues. I can change that to info but in the end, it doesn’t really change anything and doesn’t matter. And logging the version in the logs makes it easier for me to know what version of blame the person is using when they show me the logs. Gonna close this report due to the reason above. Sorry
