### ISSUE TITLE
[Suggestion] If possible, check if mod has an icon in /assets/modname and report missing entries like homepage and issues tags in the fabric.mod.json file.

### ISSUE THREAD

**Issue by K0-RR** [TelepathicGrunt/Blame#28]
You would be surprised how many modders forgot to add the icon/homepage/issues tags inside the fabric.mod.json. I have opened ~30 issues about this.

**Comment by TelepathicGrunt** [comment]
After thinking some more, I think this is stepping a bit too far lmao. Blame is more for actual gameplay issues. A missing icon in modmenu or people not listing homepages may actually be intentional and it doesn't actually affect gameplay. Seems too ridiculous to make an entire mod just print out that kind of stuff which will just annoy everyone. Gonna close this as I rather work on adding extra info for crashes or hard-to-debug issues that leads to mod conflicts/errors.

**Comment by K0-RR** [comment]
Hmm yea I think I exaggerated this hah.
