### ISSUE TITLE
[QUESTION] Does this work on clients?

### ISSUE THREAD

**Issue by srnyx** [TelepathicGrunt/Blame#39]
Does having this installed on the client work similarly to how it works on a server?

**Comment by TelepathicGrunt** [comment]
No as much if not all of of Blame's detection is for stuff that is ran serverside.

It will work for singleplayer tho as when you play single player, you game as an integrated server being ran internally for all of the game's logic and Blame can work with that. It just wont work for clients connecting to an actual server since the logic is being done on the server instead of the client connecting.

I hope this helps clarify!
