### ISSUE TITLE
Possible false positive

### ISSUE THREAD

**Issue by cheshyrp** [TelepathicGrunt/Blame#45]
Blame reports several unregistered features in the Apotheosis mod. However, the mod's author insists that everything is registered and provided the source code.  Here's a link to my bug report and the author's response.

https://github.com/Shadows-of-Fire/Apotheosis/issues/431

**Comment by TelepathicGrunt** [comment]
The funny thing is, every time someone said the configuredfeature was registered and Blame was wrong, it always turns out that Blame is right lmao. I'll take a look and see what he needs to fix

**Comment by TelepathicGrunt** [comment]
Yep. They registered their stuff incorrectly. I left details on their issue report so I'll close this one here. Hopefully they will reopen and fix their registration. Thank you for reaching out to me so I could help out!

**Comment by cheshyrp** [comment]
That was my thought as well. Especially since these so-called features are actually structures.

**Comment by cheshyrp** [comment]
My pleasure. Thank you for the help.

**Comment by TelepathicGrunt** [comment]
It's not that. Configuredfeature cannot be registered as Configuredstructures. That's an entirely different thing and the registry wouldn't even take them. The issue was that he was using the wrong name for registering which made all of his configuredfeatures in the configuredfetaure registry have the same name. Which means that all but one were kicked out of that registry due to having the same name which leads to unregistered configuredfeatures that Blame found. It is confusing
