### ISSUE TITLE
Crash with CraftBukkit

### ISSUE THREAD

**Issue by Flame115** [TelepathicGrunt/Blame#46]
My server seems to crash on startup after adding this mod. crash-log shows its due to mekanism generators and cucumber, but the mods work just fine without blame installed
[crash-2021-11-24_05.06.29-fml.txt](https://github.com/TelepathicGrunt/Blame/files/7592898/crash-2021-11-24_05.06.29-fml.txt)

**Comment by TelepathicGrunt** [comment]
Actually the issue is you are using craftbukkit. 

```
blame.mixins.json:CommandsMixin->@Inject::blame_printFailedCommandStacktrace(Lnet/minecraft/command/CommandSource;Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/mojang/brigadier/StringReader;Ljava/lang/Exception;Lnet/minecraft/util/text/IFormattableTextComponent;)V.
 Expected: [Lcom/mojang/brigadier/StringReader;, Ljava/lang/Exception;, Lnet/minecraft/util/text/IFormattableTextComponent;]
    Found: [Lorg/bukkit/event/server/ServerCommandEvent;, Ljava/lang/String;, Lcom/mojang/brigadier/StringReader;]
```

Bukkit is modifying the command class in such a way that Blame’s mixin crashes. I do not provide any support for these kinds of plug-in/forge blending projects because they often modify the game in ways that is difficult to predict and leads to the strangest errors. Sorry.

I think it would be best to not use Blame. Blame is made for a Forge only environment without any bukkit or mohist interference. 

Hopefully this helps clear up the confusion. Mekanism and cucumber are perfectly fine.

**Comment by Flame115** [comment]
alright yeah, I appreciate the quick response. :)
