### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [TelepathicGrunt/Blame#47]
My suggestion is to backport the mod to 1.12.2.

**Comment by TelepathicGrunt** [comment]
I already told you that this is impossible and why on curseforge: 

> This mod is doing checks for stuff that only exist in 1.16.2+. It makes no sense to backport it into 1.12 because 1.12 doesnt have some of these issues like world datapack parsing errors because worldgen datapacks was introduced in 1.16.2 lol

Making an issue report will not make 1.12.2 suddenly have the same codebase and issues that 1.16.2+ has. Blame is designed to mainly help with the worldgen json system that Mojang added in 1.16.2+ because it has various issues with it. Backporting Blame to 1.12.2 means Blame would be doing nothing because the stuff it looks for doesn’t exist at all.

Again, sorry but whatever issue you are having in your 1.12.2 modpack, Blame will never be able to help.
